Issue #sb-20425 fix: Too many messages in browser console log
Sunbird-Ed/SunbirdEd-portal pull request #5033
Opened 2020-08-25 10:10 UTC by VenkatKadiveti

2020-08-25 10:13 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/cbse-program/components/question-list/question-list.component.ts
> -    }, error => {
Use error block and toasterService to show the appropriate message.

2020-08-25 10:13 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/cbse-program/components/question-list/question-list.component.ts
> -      console.log(err);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:13 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/cbse-program/components/question-list/question-list.component.ts
> -      console.log(err);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:14 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/cbse-program/components/question-list/question-list.component.ts
> -      console.log(err);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel requested changes

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/cbse-program/components/question-preview/question-preview.component.ts
> -        console.log(error);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/cbse-program/components/question-preview/question-preview.component.ts
> -          console.log(error);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/dashboard/components/data-chart/data-chart.component.ts
> -          console.log(err);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/dashboard/components/data-chart/data-chart.component.ts
> -      console.log('failed to update chart data', err);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/dashboard/components/usage-reports/usage-reports.component.ts
> -      }, err => { console.log(err); });
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/groups/components/add-member/add-member.component.ts
> +           console.log(_.get(res, 'result.response'));
console log not deleted.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/learn/components/course-consumption/course-player/course-player.component.ts
> -        err => console.log(err, 'content read api failed'));
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/manage/components/user-org-management/user-org-management.component.ts
> -        console.log(error);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/manage/components/user-org-management/user-org-management.component.ts
> -        console.log(error);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/manage/components/user-org-management/user-org-management.component.ts
> -      error => {
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/manage/components/user-org-management/user-org-management.component.ts
> -        console.log(error);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/manage/components/user-org-management/user-org-management.component.ts
> -        console.log(error);
Use error block and toasterService to show the appropriate message.

2020-08-25 10:18 UTC, rajeshkumaravel commented on src/app/client/src/app/modules/manage/components/user-org-management/user-org-management.component.ts
> -          console.log(error);
Use error block and toasterService to show the appropriate message.

2020-08-25 12:28 UTC, rajeshkumaravel approved these changes

2020-08-26 04:31 UTC, VenkatKadiveti commented
Created new PR

2020-08-26 04:31 UTC, closed without merging