Issue #SH-905, #SH-891 fix: changed UI and fixed defect
Sunbird-Ed/SunbirdEd-portal pull request #5055
Opened 2020-08-27 07:25 UTC by swetha-aggidevara

2020-08-27 10:36 UTC, vinukumar-vs approved these changes

2020-08-27 10:39 UTC, vinukumar-vs requested changes

2020-08-27 10:39 UTC, vinukumar-vs commented on src/app/client/src/app/modules/groups/components/add-member/add-member.component.ts
> +        if (member.exists) {
This change requires unit-test case with proper assertion.

2020-08-31 05:09 UTC, harishgilimi approved these changes

2020-08-31 05:09 UTC, merged