Issue #DP-1414 Fix:Adopted textbooks should not be editable
Sunbird-Ed/SunbirdEd-portal pull request #5604
Opened 2020-12-09 09:58 UTC by prashantsingh03

2020-12-09 10:15 UTC, twsvaishali commented on src/app/client/src/app/modules/workspace/components/all-content/all-content.component.ts
> +        if((neww.copyType === 'shallow')){
why two brackets? @prashantsingh03 after if?

2020-12-09 10:25 UTC, twsvaishali approved these changes

2020-12-09 10:26 UTC, twsvaishali approved these changes
Approved

2020-12-10 06:33 UTC, pallakartheekreddy requested changes

2020-12-10 06:33 UTC, pallakartheekreddy commented on src/app/client/src/app/modules/workspace/components/all-content/all-content.component.ts
> +        const neww = JSON.parse(content.originData);
@prashantsingh03 please use proper variable names like `originData` insteadOf neww

2020-12-10 06:33 UTC, pallakartheekreddy commented on src/app/client/src/app/modules/workspace/components/published/published.component.ts
> +    if (typeof param.data.originData !== "undefined") {
@prashantsingh03 same here

2020-12-10 13:53 UTC, pallakartheekreddy approved these changes

2020-12-10 13:54 UTC, merged