Refactoring Course implementation logic to generalization
Sunbird-Ed/SunbirdEd-portal pull request #6355
Opened 2021-04-09 06:46 UTC by kamaleeswary

2021-04-09 08:37 UTC, balakrishna10 approved these changes

2021-04-09 08:39 UTC, balakrishna10 reviewed
check the code smells from sonar cloud and pease fix them

2021-04-09 09:37 UTC, balakrishna10 approved these changes

2021-04-14 08:54 UTC, sudip-mukherjee requested changes
Follow the commit message standard. #Issue id is missing.

2021-04-14 13:22 UTC, vinukumar-vs approved these changes

2021-04-14 13:23 UTC, merged