Issue #SB-24116 fix: DF looping issue on navigation back
Sunbird-Ed/SunbirdEd-portal pull request #6837
Opened 2021-07-07 03:33 UTC by balakrishna10

2021-07-07 07:16 UTC, vinukumar-vs requested changes

2021-07-07 07:16 UTC, vinukumar-vs commented on src/app/client/src/app/modules/shared/services/navigation-helper/navigation-helper.service.ts
> +    this._history = this._history.filter(h => !(h.url.includes('discussion-forum')))
Navigation helper service should not have any code specific to any component(like her we are using 'discussion-forum' string). We should not add any checks like this in this server.

Find the actual root cause for failure.

2021-07-07 07:16 UTC, vinukumar-vs commented on src/app/client/src/app/modules/groups/services/groups/groups.service.ts
> +      if(this.navigationhelperService['_history'].find(n => n.url.indexOf('discussion-forum') != -1)){
We should not have these kind of checks.

2021-07-09 07:18 UTC, sudip-mukherjee approved these changes

2021-07-09 09:32 UTC, vinukumar-vs approved these changes

2021-07-09 09:32 UTC, merged