Issue #SB_26945 "Copy as a Course" text is missing while user try to copy a TextBook as a course.
Sunbird-Ed/SunbirdEd-portal pull request #7286
Opened 2021-09-28 08:39 UTC by ArtiSingh23

2021-09-28 09:13 UTC, rajeevsathish requested changes

2021-09-28 09:13 UTC, rajeevsathish commented on src/app/client/src/app/modules/shared-feature/components/collection-player/collection-player.component.html
> +              {{resourceService?.frmelmnts?.lbl?.copyAsCourse}}
please use the generaliseLabelService

2021-09-28 10:05 UTC, sri-pusuluri approved these changes

2021-09-28 10:30 UTC, sri-pusuluri approved these changes

2021-09-28 10:31 UTC, sri-pusuluri commented on src/app/client/src/app/modules/shared-feature/components/collection-player/collection-player.component.html
> +              {{resourceService?.frmelmnts?.lbl?.copyAsCourse}}
i think its resolved

2021-09-29 06:37 UTC, rajeevsathish approved these changes

2021-09-29 07:23 UTC, merged