Issue #SB-28199 fix: retaining activity dashboard option on refresh
Sunbird-Ed/SunbirdEd-portal pull request #7640
Opened 2022-01-04 09:50 UTC by balakrishna10

2022-01-05 04:46 UTC, vinukumar-vs approved these changes

2022-01-05 04:46 UTC, vinukumar-vs commented on src/app/client/src/app/modules/groups/components/activity/activity-list/activity-list.component.ts
> +      sessionStorage.setItem(sessionKeys.ISACTIVITYADDED, 'true') // setting this value to enable or disable the activity dashboard button in activity-dashboard directive
Dont use sessions for more info.

2022-01-05 04:47 UTC, vinukumar-vs requested changes
Lets check what information are we dumping in session.

2022-02-02 11:56 UTC, rajeevsathish requested changes

2022-02-02 11:56 UTC, rajeevsathish commented on src/app/client/src/app/modules/groups/components/activity/activity-search/activity-search.component.ts
> +import { sessionKeys } from '../../..';
please make the correct import

2022-02-03 04:57 UTC, balakrishna10 commented on src/app/client/src/app/modules/groups/components/activity/activity-search/activity-search.component.ts
> +import { sessionKeys } from '../../..';
updated now.

2022-02-03 05:20 UTC, rajeevsathish approved these changes

2022-02-03 05:20 UTC, merged