Story #SB-28542 fix: program role enhancement
Sunbird-Ed/SunbirdEd-portal pull request #7871
Opened 2022-03-10 08:01 UTC by rakeshSgr

2022-03-10 11:28 UTC, rajeevsathish requested changes

2022-03-10 11:28 UTC, rajeevsathish commented on src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.ts
> +fdescribe('DatasetsComponent', () => {
why is this a fdescribe

2022-03-10 11:31 UTC, rakeshSgr commented on src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.spec.ts
> +fdescribe('DatasetsComponent', () => {
resolved

2022-03-15 09:48 UTC, rajeevsathish approved these changes

2022-03-15 09:49 UTC, merged