Issue #ED-1613 fix: Request getting timed out for district with more than 17 character length
Sunbird-Ed/SunbirdEd-portal pull request #8618
Opened 2023-04-10 11:30 UTC by 5Amogh

# SunbirdEd - Portal
---

### Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
---

### Please choose applicable option 
#### Example
- [x] Applicable
- [ ] Not applicable

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-10 12:51 UTC, vinukumar-vs requested changes
No unit tests has written for hot-fix also?

2023-04-10 13:21 UTC, 5Amogh commented on src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
> +    this.tag = tagId.length > 79 ? tagId.substring(0,79) : tagId
Unit tests have been added, Please check
.
As the solution filter is a mandatory field before executing this function we already will have a solution value thus it'll not be undefined.

2023-04-10 13:23 UTC, 5Amogh commented on src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
> +    this.tag = tagId.length > 79 ? tagId.substring(0,79) : tagId
The tagId to request a report allows only upto 79 characters in the URL thus we had to trim the rest of the other characters which were causing the timed out issue

2023-04-10 17:43 UTC, vinukumar-vs requested changes

2023-04-10 17:43 UTC, vinukumar-vs commented on src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
> +    this.tag = tagId.length > 79 ? tagId.substring(0,79) : tagId
But this is not a good way of trimming. Either you limit the user input field length(_.get(this.reportForm, 'controls.solution.value')) or dont add too many parameter to tagID.

2023-04-11 03:38 UTC, 5Amogh commented on src/app/client/src/app/modules/program-dashboard/components/program-datasets/program-datasets.component.ts
> +    this.tag = tagId.length > 79 ? tagId.substring(0,79) : tagId
The solution value is not a user entered value it's the id of the solution selected and we restrict that.
and yes this is only for short term, we are considering a long term approach using md5 hashing and migration of existing reports which have been generated using this approach.

Please check this discussion where we have asked the approaches we need to take for long term solution 
 https://github.com/orgs/Sunbird-Obsrv/discussions/62

the sample of tagId = 'xxxx9beb823d601f0af5xxxx_xxxx3686-0e88-4482-b86f-b34bbfb7xxxx_bengaluru urban s'

2023-04-11 07:24 UTC, vinukumar-vs commented
@kirang20 @vijiurs 
As discussed, this is the temporary solution for hot-fix to unblock the on-going programs. Immediately annother hot-fix will be pushed with properly as discussed in the below thread.
https://github.com/orgs/Sunbird-Obsrv/discussions/62

@vrayulu @SanthoshVasabhaktula @Krishnaj20

2023-04-11 08:34 UTC, vinukumar-vs approved these changes

2023-04-11 08:35 UTC, merged