Issue #ED-419 feat:PII consent for observation details page
Sunbird-Ed/SunbirdEd-portal pull request #8676
Opened 2023-05-08 14:35 UTC by 5Amogh

# SunbirdEd - Portal
---

### PII consent for observation details page
---

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-09 07:18 UTC, rajeevsathish reviewed
please update the changes

2023-05-09 07:20 UTC, rajeevsathish requested changes
please update the comment

2023-05-09 07:20 UTC, rajeevsathish commented on src/app/helpers/whitelistApis.js
> +    "/assessment/users/mlcore/v1/solutions/:id":{
why do you need check for ALL role?

2023-05-09 07:35 UTC, 5Amogh commented on src/app/helpers/whitelistApis.js
> +    "/assessment/users/mlcore/v1/solutions/:id":{
In case user does not have public role

2023-05-09 08:48 UTC, rajeevsathish commented on src/app/client/src/app/modules/observation/components/observation-details/observation-details.component.ts
> +    this.consentConfig = { tncLink: _.get(this.resourceService, 'frmelmnts.lbl.privacyPolicy'), tncText: _.get(this.resourceService, 'frmelmnts.lbl.programConsent') };
how is the instance value be added?

2023-05-09 09:28 UTC, 5Amogh commented on src/app/client/src/app/modules/observation/components/observation-details/observation-details.component.ts
> +    this.consentConfig = { tncLink: _.get(this.resourceService, 'frmelmnts.lbl.privacyPolicy'), tncText: _.get(this.resourceService, 'frmelmnts.lbl.programConsent') };
using interpolate pipe @rajeevsathish

2023-05-09 09:31 UTC, 5Amogh commented on src/app/resourcebundles/data/consumption/en.properties
> +frmelmnts.lbl.programConsent = I consent to share my details with the administrators of this program. All administrators are bound by the privacy policy and DIKSHA terms of use of my data.
I have updated this one as well

2023-05-12 03:59 UTC, rajeevsathish approved these changes

2023-05-12 03:59 UTC, merged