Rel 7.0.0 for Delete User ED-2848
Sunbird-Ed/SunbirdEd-portal pull request #8997
Opened 2023-11-10 05:28 UTC by rajeevsathish

# SunbirdEd - Portal
---

### Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
---

### Please choose applicable option 
#### Example
- [x] Applicable
- [ ] Not applicable

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Enhancement (additive changes to improve performance)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-16 06:47 UTC, sri-pusuluri submitted a review, later dismissed

2023-11-17 09:30 UTC, vinukumar-vs requested changes

2023-11-17 09:30 UTC, vinukumar-vs commented on src/app/routes/learnerRoutes.js
> +        if (req.method === 'DELETE' && proxyRes.statusCode === 404 && (typeof data.message === 'string' && data.message.toLowerCase() === 'API not found with these values'.toLowerCase())) res.redirec
Only check for statusCode here for failures..
Are we handling only 403?

Remove other check req.method, data.message etc.

2023-11-17 09:30 UTC, vinukumar-vs approved these changes

2023-11-17 09:31 UTC, merged